spring:
  application:
    name: pos-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/